name: make C

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout to get acess to repository files
    - name: checkout 
      uses: actions/checkout@v3
    # install dependencies
    - name: install-libs
      run: |
        sudo apt-get update
        sudo apt-get install libglfw3-dev || sudo apt get install libglfw3
    # build it!
    - name: build application
      run: make
    # and test (with dummy X server)
    - name: test application
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        make test
